-- ACTIVIDAD 1
/*
DESCARGAR DE AVA EL SCRIPT DE CREACION DE LA BASE DESDE
LA ACTIVIDAD 3.2 DE LA EXPERIENCIA 3

CREAR EL USUARIO QUE SERÁ DUEÑO DE LA BASE DE DATOS.
DEBE LLAMARSE KOPERA_DB CON LA PASSWORD QUE UD. DEFINA, EL USUARIO DEBE 
UTILIZAR EL TABLESPACE USERS COMO TABLESPACE DE DATOS POR DEFECTO,  EL TABLESPACE
TEMP COMO TABLESPACE TEMPORAL Y SE LE DEBE ASIGNAR CUOTA
ILIMITADA EN EL TABLESPACE DE DATOS
 
EL USUARIO DEBE TENER PRIVILEGIOS PARA PARA CREAR UNA SESION Y PARA CREAR TABLAS. 
EJECUTE EL SCRIPT Y DETERMINE SI DEBE ENTREGAR ALGUN OTRO PRIVILEGIO 
PARA QUE EL SCRIPT FUNCIONE NORMALMENTE
*/

DROP USER KOPERA_DB CASCADE;
CREATE USER KOPERA_DB IDENTIFIED BY DUOC
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO KOPERA_DB;
GRANT CREATE TABLE TO KOPERA_DB;
GRANT CREATE SEQUENCE TO KOPERA_DB;


-- ACTIVIDAD 2
--CREAR UN PERFIL LLAMADO KOPERA_PROFILE. EL PERFIL DEBE LIMITAR EL ACCESO A RECURSOS
--2 SESIONES SIMULTANEAS, 15 MINUTOS DE SESION, 1 MINUTO DE 
--TIEMPO DE INACTIVIDAD Y RESPECTO DE LAS CONTRASEÑAS 
--DEBE PERMITIR SOLO 3 INTENTOS FALLIDOS DE CONEXION, 

DROP PROFILE KOPERA_PROFILE;
CREATE PROFILE KOPERA_PROFILE LIMIT
    SESSIONS_PER_USER 2
    CONNECT_TIME 15
    IDLE_TIME 1
    FAILED_LOGIN_ATTEMPTS 3;


  
-- ACTIVIDAD 3   
--CREAR 10 USUARIOS LLAMADOS USER_1, USER_2 RESPECTIVAMENTE
--QUE USEN LOS MISMOS TABLESPACES ASIGNADOS AL USUARIO DUEÑO 
--DE LA BASE, CON UNA QUOTA DE 50 MEGAS EN EL TABLESPACE DE DATOS.
--SE LES DEBE ASIGNAR EL PERFIL CREADO. (NO ES NECESARIO QUE CREE
--LOS 10, BASTA QUE CREE UNO PARA REALIZAR EL TESTING

--LOS USUARIOS DEBEN SER CAPACES DE CREAR UNA SESION  Y CREAR
--PROCEDIMIENTOS. ADEMAS DEBEN TENER PRIVILEGIOS PARA VER
--LOS DATOS DE LAS TABLAS PRODUCTO_INVERSION, PRODUCTO_INVERSION_CLIENTE
--Y MOVIMIENTO. REFLEXIONE SOBRE QUÉ OBJETO DEBE CREAR PARA ASIGNAR 
--LOS PERMISOS A TODOS LOS USUARIOS.

--LOS USUARIOS NO DEBEN PODER USAR LOS NOMBRES ORIGINALES DE LAS TABLAS
--RAZÓN POR LA CUAL DEBEN UTILIZAR SINONIMOS, CONSIDERE QUE TIPO
--DE SINONIMO DEBE CREAR.

DROP ROLE ROL_KOPERA;
CREATE ROLE ROL_KOPERA;
GRANT CREATE SESSION TO ROL_KOPERA;
GRANT CREATE PROCEDURE TO ROL_KOPERA;
GRANT SELECT ON KOPERA_DB.PRODUCTO_INVERSION TO ROL_KOPERA;
GRANT SELECT ON KOPERA_DB.PRODUCTO_INVERSION_CLIENTE TO ROL_KOPERA;
GRANT SELECT ON KOPERA_DB.MOVIMIENTO TO ROL_KOPERA;

-- CREACION DEL USUARIO USER1
DROP USER USER_1 CASCADE;
CREATE USER USER_1 IDENTIFIED BY DUOC
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 50M ON USERS
PROFILE KOPERA_PROFILE;

GRANT ROL_KOPERA TO USER_1;
ALTER USER USER_1 ACCOUNT UNLOCK;

-- CREACION DE SINONIMOS PUBLICOS
CREATE OR REPLACE PUBLIC SYNONYM PRODUCTO_INVERSION 
    FOR KOPERA_DB.PRODUCTO_INVERSION;
CREATE OR REPLACE PUBLIC SYNONYM PRODUCTO_INVERSION_CLIENTE 
    FOR KOPERA_DB.PRODUCTO_INVERSION_CLIENTE;
CREATE OR REPLACE PUBLIC SYNONYM MOVIMIENTO
    FOR KOPERA_DB.MOVIMIENTO;

-- ACTIVIDAD 4
--CREAR UN USUARIO LLAMADO CONSULTOR. EL USUARIO
--DEBE OCUPAR LOS MISMOS TABLESPACES QUE LOS USUARIOS ANTERIORES,
--TENER CUOTA ILIMITADA EN EL TABLESPACE DE DATOS RESPECTIVO.
--DEBE TENER PRIVILEGIOS PARA CREAR VISTAS, PARA CREAR TRABAJOS PROGRAMADOS,
--CUBOS Y PERFILES

DROP USER CONSULTOR CASCADE;
CREATE USER CONSULTOR IDENTIFIED BY DUOC
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE VIEW TO CONSULTOR;
GRANT CREATE JOB TO CONSULTOR;
GRANT CREATE CUBE TO CONSULTOR;
GRANT CREATE PROFILE TO CONSULTOR;
GRANT CREATE SESSION TO CONSULTOR;

/*
-- ACIVIDAD 5
--EL USUARIO CONSULTOR DEBE SER CAPAZ DE CREAR UNA VISTA
--EN SU ESQUEMA QUE MUESTRE LOS DATOS DE LOS CLIENTES
--QUE POSEEN UN TOTAL DE CREDITOS EN EL AÑO ANTERIOR
--MAYOR A 5000000. EL INFORME DEBE MOSTRAR NRO DE CLIENTE,
--RUT COMPLETO, NOMBRE COMPLETO, FECHA DE NACIMIENTO,
--FONO_CONTACTO, PROFESION Y TIPO DE CONTRATO, JUNTO
--CON EL NUMERO DE CREDITOS QUE POSEE EN EL AÑO ANTERIOR
--Y EL MONTO TOTAL DE DICHOS CREDITOS ORDENANDO POR EL APELLIDO PATERNO

--PARA CREAR LA VISTA EL USUARIO DEBE TENER LOS PRIVILEGOS 
--DE OBJETO NECESARIOS Y NO PODRÁ USAR LOS NOMBRES ORIGINALES
--DE LAS TABLAS, DEBE USAR SINONIMOS QUE LE PERMITAN EL ACCESO
--EXCLUSIVO DADO QUE SOLO EL ESTÁ AUTORIZADO A CREAR Y MODIFICAR
--ESTE INFORME
*/

CREATE OR REPLACE SYNONYM CONSULTOR.CLIENTE FOR KOPERA_DB.CLIENTE;
CREATE OR REPLACE SYNONYM CONSULTOR.CREDITO_CLIENTE FOR KOPERA_DB.CREDITO_CLIENTE;
CREATE OR REPLACE SYNONYM CONSULTOR.PROFESION_OFICIO FOR KOPERA_DB.PROFESION_OFICIO;
CREATE OR REPLACE SYNONYM CONSULTOR.TIPO_CONTRATO FOR KOPERA_DB.TIPO_CONTRATO;

GRANT SELECT ON CONSULTOR.CLIENTE TO CONSULTOR WITH GRANT OPTION;
GRANT SELECT ON CONSULTOR.CREDITO_CLIENTE TO CONSULTOR WITH GRANT OPTION;
GRANT SELECT ON CONSULTOR.PROFESION_OFICIO TO CONSULTOR WITH GRANT OPTION;
GRANT SELECT ON CONSULTOR.TIPO_CONTRATO TO CONSULTOR WITH GRANT OPTION;

-- ACTIVIDAD NRO. 6
/*
CREAR UN USUARIO LLAMADO OPERADOR QUE USE LOS MISMOS TABLESPACES
ASIGNADOS A LOS USUARIOS ANTERIORES CON UNA CUOTA DE 100M. 
DEBE TENER PRIVILEGIOS PARA CREAR UNA SESION Y PARA SELECCIONR LOS DATOS DE LA VISTA
V_CREDITOS DEL USUARIO CONSULTOR. EL USUARIO NO PODRÁ USAR EL NOMBRE ORIGINAL
DE LA VISTA POR LO QUE DEBE ACCEDERLA SOLO ÉL, MEDIANTE UN SINONIMO LLAMADO SYN_CREDITOS.  

*/
DROP USER OPERADOR CASCADE;
CREATE USER OPERADOR IDENTIFIED BY DUOC
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 100M ON USERS;

GRANT CREATE SESSION TO OPERADOR;

CREATE OR REPLACE SYNONYM OPERADOR.SYN_CREDITOS FOR CONSULTOR.VISTA_CONSULTOR;

GRANT SELECT ON OPERADOR.SYN_CREDITOS TO OPERADOR;








