-- DEMO DEFUNCIONES DE GRUPO
--- SINTAXIS DE SELECT
/*
SELECT campo1  alias1, campo2 alias2, campo_n
FROM nombre_tabla
WHERE condicion (FILTRA LAS FILAS ALMACENADAS)
GROUP BY campo1, campo2 (PERMITE FORMAR GRUPOS DE FILAS)
HAVING condicion (FILTRA LOS GRUPOS FORMADOS)
ORDER BY campo1, campo2;

-- OBSERVACIONES
-- EL GRUPO PUEDE SER LA TOTALIDAD DE UNA TABLA O SE PUEDEN FORMAR GRUPOS USANDO GROUP BY

funciones
COUNT   SIRVE PARA CONTAR LAS FILAS QUE CUMPLEN UNA CONDICION
SUM     SIRVE PARA TOTALIZAR UN CAMPO O EXPRESION
AVG     PERMITE CALCULAR EL PROMEDIO DE UN CAMPO O EXPRESION
MAX     PERMITE DETERMINAR EL VALOR MAXIMO DE UN CAMPO O EXPRESION
MIN     PERMITE DETERMINAR EL VALOR MINIMO DE UN CAMPO O EXPRESION

SUM Y AVG SOLO PUEDEN USAR CON CAMPOS O EXPRESIONES NUMERICAS
COUNT, MAX, MIN PUEDEN UTILIZARSE CON CUALQUIER TIPO DE CAMPO O EXPRESION

GROUP BY EXISTE CON INDEPENDENCIA DE HAVING, PERO HAVING REQUIERE LA EXISTENCIA DE GROUP BY
*/
-- NINGUNA DE LAS FUNCIONES CONSIDERA LOS VALORES NULOS SALVO CUANDO USO COUNT(*)

-- CUANTOS EMPLEADOS HAY EN LA EMPRESA?
SELECT 
    COUNT(*)
FROM EMPLOYEES;

SELECT
    COUNT(NVL(COMMISSION_PCT, 0)) NRO_EMPLEADOS
FROM EMPLOYEES;

--- CUANTOS EMPLEADOS GANAS MAS DE 12000
SELECT 
    COUNT(EMPLOYEE_ID) 
FROM EMPLOYEES
WHERE SALARY > 12000;

--- DETERMINAR SUELDO MAXIMO, SUELDO MIN, PROMEDIO DEL SUELDO Y TOTAL DE LOS SUELDOS ENTRE TODOS LOS EMPLEADOS
SELECT 
    MAX(SALARY) SUELDOMAX,
    MIN(SALARY) SUELDOMIN,
    ROUND(AVG(SALARY)) PROMEDIO,
    SUM(SALARY) TOTAL_SUELDOS
FROM EMPLOYEES;

-- OBTENER LA FECHA DE CONTRATO MAS RECIENTE Y EL ULTIMO APELLIDO REGISTRADO EN LA BASE, EL MAS CERCANO A LA Z
SELECT 
    MAX(HIRE_DATE) FECHA_MAS_RECIENTE,
    MIN(LAST_NAME) FECHA_MAS_ANTIGUA,
    COUNT(FIRST_NAME) NRO_EMPLEADOS
FROM EMPLOYEES;


-- OBTENER NUMERO DE EMPLEADOS Y SUELDO PROMEDIO DE LOS EMPLEADOS EN CADA UNO DE LOS DEPARTAMENTOS DE LA EMPRESA
SELECT 
    DEPARTMENT_ID DEPARTAMENTO,
    COUNT(EMPLOYEE_ID) NRO_EMPLEADOS,
    ROUND(AVG(SALARY))PROMEDIO_SUELDO
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- OBTENER SOLO LOS DEPARTAMENTOS QUE POSEEN UN PROMEDIO DE SUELDOS DE LOS EMPLEADOS SUPERIOR A 12000
SELECT 
    DEPARTMENT_ID DEPARTAMENTO,
    COUNT(EMPLOYEE_ID) NRO_EMPLEADOS,
    ROUND(AVG(SALARY))PROMEDIO_SUELDO
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING ROUND(AVG(SALARY)) > 12000;

-- CUANTOS DEPARTAMENTOS POSEEN EMPLEADOS
SELECT 
    COUNT(DISTINCT DEPARTMENT_ID)
FROM EMPLOYEES;



