-- DEMO DE CREACION DE OBJETOS EN LA BASE DE DATOS
--- VISTAS, SECUENCIAS Y SINONIMOS


-- SINTAXIS DE CREACION DE UNA VISTA
/*
DROP VIEW nombre_vista;

CREATE [OR REPLACE] [FORCE|NOFORCE] VIEW nombre_visita
            [(alias[, alias]...)]
AS subconsulta
[WITH CHECK OPTION [CONSTRAINT nombre_constraint ]]
[WITH READ ONLY [CONSTRAINT nombre_constraint ]];
*/

/*
HAY DOS TIPOS DE VISTAS: VISTAS SIMPLES Y VISTAS COMPLEJAS

UNA VISTA SIMPLE SELECCIONA TODOS LOS CAMPOS DE UNA UNICA TABLA, 
CON INDEPENCIA DE CUANTAS TABLAS PARTICIPAN DE LA VISTA 
Y NO DEBE TENER CALCULOS NI USO DE FUNCIONES. UNA VISTA SIMPLE PERMITE TODAS LAS OPERACIONES DML
*/

-- LA GERENCIA REQUIERE UN INFORME QUE MUESTRE TODOS LOS DATOS DE LOS EMPLEADOS. EL INFORME SE DEBE PREPARAR MEDIANTE UNA VISTA LLAMADA V_EMPLEADOS

DROP VIEW V_EMPLEADOS;
CREATE VIEW V_EMPLEADOS AS
SELECT *
FROM EMPLOYEES;

-- OPERACIONES CON UNA VISTA

SELECT * FROM V_EMPLEADOS;

SELECT * FROM V_EMPLEADOS WHERE SALARY > 12000;

SELECT 
    V.EMPLOYEE_ID "ID EMPLEADO",
    V.LAST_NAME || ' ' || V.FIRST_NAME NOMBRE,
    J.JOB_TITLE CARGO
FROM V_EMPLEADOS V JOIN JOBS J 
ON V.JOB_ID = J.JOB_ID;

-- OPERACIONES DML A TRAVES DE UNA LISTA
INSERT INTO V_EMPLEADOS 
VALUES(999, 'Paz', 'Guerra', 'PGUERRA@', '944332211', '01032000', 'IT_PROG', '15000', NULL, 100, 30);

SELECT * FROM V_EMPLEADOS;
UPDATE V_EMPLEADOS SET SALARY = 20000 WHERE EMPLOYEE_ID = 999;
DELETE V_EMPLEADOS WHERE EMPLOYEE_ID = 999;

-- LA GERENCIA REQUIERE UN INFORME QUE MUESTRE ID, NOMBRE COMPLETO DEL EMPLEADO, SALARIO, NOMBRE DEL CARGO QUE EJERCE Y NOMBRE DEL DEPARTAMENTO 
-- EN QUE TRABAJA. CREE UNA VISTA LLAMADA V_EMPLEADOS2 PARA SATISFACER EL REQUERIMIENTO

-- PRIMERA OPCION DE ALIAS
CREATE VIEW V_EMPLEADOS2 (ID_EMPLEADO, NOMBRE_EMPLEADO, SUELDO, CARGO, DEPARTAMENTO) AS 
SELECT 
    E.EMPLOYEE_ID,
    E.LAST_NAME || ' ' || E.FIRST_NAME,
    E.SALARY,
    J.JOB_TITLE,
    D.DEPARTMENT_NAME   
FROM EMPLOYEES E JOIN JOBS J
ON E.JOB_ID = J.JOB_ID
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- SEGUNDA OPCION DE ALIAS
DROP VIEW V_EMPLEADOS3;
CREATE VIEW V_EMPLEADOS3 AS 
SELECT 
    E.EMPLOYEE_ID ID_EMPLEADO,
    E.LAST_NAME || ' ' || E.FIRST_NAME NOMBRE_EMPLEADO,
    E.SALARY SUELDO,
    ROUND(E.SALARY * 0.3) BONO,
    J.JOB_TITLE CARGO,
    D.DEPARTMENT_NAME DEPARTAMENTO   
FROM EMPLOYEES E JOIN JOBS J
ON E.JOB_ID = J.JOB_ID
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


-- USO DE LA PRIMERA CLAUSULA WITH CHECK OPTION 
-- PRIMER NIVEL DE SEGURIDAD 
-- CREAR UNA VISTA LLAMADA V_EMPLEADOS 4
-- QUE MUESTRE ID, NOMBRE COMPLETO, SALARIO, ID DEL DEPARTAMENTO DE TODOS LOS EMPLEADOS DEL DEPARTAMENTO 50

CREATE OR REPLACE VIEW V_EMPLEADOS4 AS 
SELECT 
    EMPLOYEE_ID ID,
    LAST_NAME || ' ' || FIRST_NAME NOMBRE,
    SALARY SUELDO,
    DEPARTMENT_ID DEPARTAMENTO
FROM EMPLOYEES 
WHERE DEPARTMENT_ID = 50
WITH CHECK OPTION;











