-- CREACION DEL PRIMER USUARIO DUEÑO DE LA BD
DROP USER MDY2131_P3_1 CASCADE;
CREATE USER MDY2131_P3_1 IDENTIFIED BY DUOC;
ALTER USER MDY2131_P3_1 DEFAULT TABLESPACE USERS;
ALTER USER MDY2131_P3_1 TEMPORARY TABLESPACE TEMP;
ALTER USER MDY2131_P3_1 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO MDY2131_P3_1;
GRANT CREATE SEQUENCE TO MDY2131_P3_1;
GRANT CREATE TABLE TO MDY2131_P3_1;

-- CREACION DEL SEGUNDO USUARIO
DROP USER MDY2131_P3_2 CASCADE;
CREATE USER MDY2131_P3_2 IDENTIFIED BY DUOC;
ALTER USER MDY2131_P3_2 DEFAULT TABLESPACE USERS;
ALTER USER MDY2131_P3_2 TEMPORARY TABLESPACE TEMP;
ALTER USER MDY2131_P3_2 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO MDY2131_P3_2;
GRANT CREATE PROCEDURE TO MDY2131_P3_2;
GRANT CREATE TRIGGER TO MDY2131_P3_2;
GRANT CREATE VIEW TO MDY2131_P3_2;
GRANT CREATE MATERIALIZED VIEW TO MDY2131_P3_2;
GRANT SELECT ON MDY2131_P3_1.CLIENTE TO MDY2131_P3_2 WITH GRANT OPTION;
GRANT SELECT ON MDY2131_P3_1.PROFESION_OFICIO TO MDY2131_P3_2 WITH GRANT OPTION;
GRANT SELECT ON MDY2131_P3_1.TIPO_CONTRATO TO MDY2131_P3_2 WITH GRANT OPTION;
GRANT SELECT ON MDY2131_P3_1.PRODUCTO_INVERSION_CLIENTE TO MDY2131_P3_2 WITH GRANT OPTION;
GRANT SELECT,INSERT,UPDATE,DELETE ON MDY2131_P3_1.CREDITO_CLIENTE TO MDY2131_P3_2;
GRANT SELECT ON MDY2131_P3_1.PRODUCTO_INVERSION TO MDY2131_P3_2;
GRANT SELECT ON MDY2131_P3_1.SUCURSAL TO MDY2131_P3_2;
GRANT SELECT ON MDY2131_P3_1.REGION TO MDY2131_P3_2;
GRANT INSERT,UPDATE,DELETE ON MDY2131_P3_1.CUOTA_CREDITO_CLIENTE TO MDY2131_P3_2;

CREATE OR REPLACE SYNONYM MDY2131_P3_2.CLIENTE 
   FOR MDY2131_P3_1.CLIENTE;
CREATE OR REPLACE SYNONYM MDY2131_P3_2.PROFESION_OFICIO 
   FOR MDY2131_P3_1.PROFESION_OFICIO;
CREATE OR REPLACE SYNONYM MDY2131_P3_2.TIPO_CONTRATO 
   FOR MDY2131_P3_1.TIPO_CONTRATO;
CREATE OR REPLACE SYNONYM MDY2131_P3_2.PRODUCTO_INVERSION_CLIENTE 
   FOR MDY2131_P3_1.PRODUCTO_INVERSION_CLIENTE;

-- CREACION DE LA VISTA
CREATE OR REPLACE VIEW V_CATEGORIAS AS
SELECT TO_CHAR(CL.NUMRUN, '09G999G999')||'-'||CL.DVRUN RUN_CLIENTE,
       CL.PNOMBRE||' '||CL.SNOMBRE||' '||CL.APPATERNO||' '||CL.APMATERNO NOMBRE_CLIENTE,
       pof.nombre_prof_ofic profesion_oficio,
       tc.nombre_tipo_contrato tipo_contrato,
       SUM(pc.monto_total_ahorrado) MONTO_TOTAL_AHORRADO,
       CASE
         WHEN SUM(pc.monto_total_ahorrado) BETWEEN 100000 AND 1000000 THEN 'BRONCE'
         WHEN SUM(pc.monto_total_ahorrado) BETWEEN 1000001 AND 4000000 THEN 'PLATA'
         WHEN SUM(pc.monto_total_ahorrado) BETWEEN 4000001 AND 8000000 THEN 'SILVER'
         WHEN SUM(pc.monto_total_ahorrado) BETWEEN 8000001 AND 15000000 THEN 'GOLD'
         WHEN SUM(pc.monto_total_ahorrado) > 15000000 THEN 'PLATINUM'
        END CATEGORIA_CLIENTE
FROM CLIENTE CL JOIN PRODUCTO_INVERSION_CLIENTE PC
ON PC.NRO_CLIENTE = CL.NRO_CLIENTE
JOIN PROFESION_OFICIO POF ON POF.COD_PROF_OFIC = CL.COD_PROF_OFIC
JOIN TIPO_CONTRATO TC ON TC.COD_TIPO_CONTRATO = CL.COD_TIPO_CONTRATO 
WHERE TO_CHAR(pc.fecha_solic_prod, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY') -1 
group by TO_CHAR(CL.NUMRUN, '09G999G999')||'-'||CL.DVRUN, 
         CL.PNOMBRE,CL.SNOMBRE,CL.APPATERNO,CL.APMATERNO, pof.nombre_prof_ofic, tc.nombre_tipo_contrato
ORDER BY cl.appaterno;

-- REQUERIMIENTO NRO 3
CREATE PROFILE KOPERA_PROFILE LIMIT
  SESSIONS_PER_USER 1
  CONNECT_TIME 15
  PASSWORD_LIFE_TIME 7
  FAILED_LOGIN_ATTEMPTS 2;

CREATE ROLE ROL_KOPERA;
GRANT CREATE SESSION TO ROL_KOPERA;
GRANT SELECT ON MDY2131_P3_1.CLIENTE TO ROL_KOPERA;
GRANT SELECT ON MDY2131_P3_1.CREDITO_CLIENTE TO ROL_KOPERA;
GRANT SELECT ON MDY2131_P3_1.PRODUCTO_INVERSION TO ROL_KOPERA;

CREATE OR REPLACE PUBLIC SYNONYM CLIENTE FOR MDY2131_P3_1.CLIENTE;
CREATE OR REPLACE PUBLIC SYNONYM CREDITO_CLIENTE FOR MDY2131_P3_1.CREDITO_CLIENTE;
CREATE OR REPLACE PUBLIC SYNONYM PRODUCTO_INVERSION FOR MDY2131_P3_1.PRODUCTO_INVERSION;

-- CREACION DEL USUARIO CONSULTOR
DROP USER CONSULTOR_1 CASCADE;
CREATE USER CONSULTOR_1 IDENTIFIED BY DUOC;
ALTER USER CONSULTOR_1 DEFAULT TABLESPACE USERS;
ALTER USER CONSULTOR_1 TEMPORARY TABLESPACE TEMP;
ALTER USER CONSULTOR_1 QUOTA UNLIMITED ON USERS;
ALTER USER CONSULTOR_1 PROFILE KOPERA_PROFILE;
GRANT ROL_KOPERA TO CONSULTOR_1;
GRANT SELECT ON MDY2131_P3_2.V_CATEGORIAS TO CONSULTOR_1;
CREATE OR REPLACE SYNONYM CONSULTOR_1.V_CATEGORIAS FOR MDY2131_P3_2.V_CATEGORIAS;

ALTER USER CONSULTOR_1 ACCOUNT UNLOCK;

-- COMO CONSULTOR
SELECT * FROM CLIENTE;
SELECT * FROM CREDITO_CLIENTE;
SELECT * FROM V_CATEGORIAS;

-- CREACION DE INDICES
SELECT TO_CHAR(crc.fecha_otorga_cred,'MMYYYY') "MES TRANSACCIÓN",
c.nombre_credito "TIPO CREDITO",
SUM(crc.monto_credito) "MONTO SOLICITADO CREDITO",
SUM(CASE WHEN crc.monto_credito BETWEEN 100000 AND 1000000 THEN ROUND(crc.monto_credito*0.01)
WHEN crc.monto_credito BETWEEN 1000001 AND 2000000 THEN ROUND(crc.monto_credito*0.02)
WHEN crc.monto_credito BETWEEN 2000001 AND 4000000 THEN ROUND(crc.monto_credito*0.03)
WHEN crc.monto_credito BETWEEN 4000001 AND 6000000 THEN ROUND(crc.monto_credito*0.04)
ELSE ROUND(crc.monto_credito*0.07) END) "APORTE A LA SBIF"
FROM credito_cliente crc JOIN credito c
ON crc.cod_credito=c.cod_credito
WHERE crc.monto_credito > (SELECT ROUND(AVG(monto_credito))
FROM credito_cliente)
GROUP BY TO_CHAR(crc.fecha_otorga_cred,'MMYYYY'), c.nombre_credito
ORDER BY TO_CHAR(crc.fecha_otorga_cred,'MMYYYY'), c.nombre_credito;

CREATE INDEX IDX_CREDITO_CLIENTE ON CREDITO_CLIENTE ( monto_credito );

SELECT EXTRACT(YEAR FROM SYSDATE) "AÑO TRIBUTARIO",
TO_CHAR(c.numrun,'09G999G999') || '-' || UPPER(c.dvrun) "RUN CLIENTE",
INITCAP(c.pnombre || ' ' || SUBSTR(c.snombre,1,1) || '. ' || c.appaterno || ' ' || c.apmaterno) "NOMBRE CLIENTE",
COUNT(pic.nro_cliente) "TOTAL PROD. INV AFECTOS IMPTO",
LPAD(TO_CHAR(SUM(pic.monto_total_ahorrado),'$999G999G999'),21, ' ') "MONTO TOTAL AHORRADO"
FROM cliente c JOIN producto_inversion_cliente pic
ON c.nro_cliente=pic.nro_cliente
WHERE EXTRACT(YEAR FROM pic.fecha_solic_prod) = EXTRACT(YEAR FROM SYSDATE)
GROUP BY numrun,c.dvrun,c.pnombre,c.snombre,c.appaterno,c.apmaterno
ORDER BY c.appaterno;

CREATE INDEX ID_PROD_INV_CLIENTE ON PRODUCTO_INVERSION_CLIENTE ( EXTRACT(YEAR FROM fecha_solic_prod) );




